Catkin-ProjectName: rx
Version: 1.8.6
Depends: catkin, ros_comm, rospack, wxwidgets, swig-wx
Description: GUI tools for ROS - rxbag, rxplot, rxgraph, and others
Author: Ken Conley et al
Maintainer: Ken Conley <kwc@willowgarage.com>
Homepage: http://ros.org/wiki/rx


Catkin-CopyrightType: willowgarage
Catkin-DebRulesType: cmake
